# Generated by Django 4.2.23 on 2025-07-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gig',
            table='app_gig',
        ),
    ]
