# Generated by Django 4.2.23 on 2026-01-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='jobtype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='app.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jobtype',
            unique_together={('organization', 'code')},
        ),
    ]
