# Generated by Django 4.2.23 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_result_desc_mpesatransaction_customer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
