# Generated by Django 4.2.23 on 2025-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mpesatransaction_mpesa_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='mpesa_code',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
