# Generated by Django 4.2.23 on 2025-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_mpesatransaction_mpesa_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100)),
            ],
        ),
    ]
