# Generated by Django 4.2.23 on 2025-07-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='app.organization'),
        ),
    ]
