# Generated by Django 4.2.23 on 2025-07-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gig_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='worker',
        ),
    ]
