# Generated by Django 4.2.23 on 2025-07-23 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_gig_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
