# Generated by Django 4.2.23 on 2025-07-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_gig_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='app.organization'),
            preserve_default=False,
        ),
    ]
