# Generated by Django 4.2.23 on 2025-08-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gig_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA/payments/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA/profiles/'),
        ),
    ]
