# Generated by Django 4.2.23 on 2025-08-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_gig_is_completed_alter_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='is_completed',
        ),
    ]
