# Generated by Django 4.2.23 on 2025-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_gig_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaNewTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.TextField()),
                ('raw_callback', models.JSONField()),
            ],
        ),
    ]
