# Generated by Django 4.2.23 on 2025-08-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mpesanewtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
        migrations.DeleteModel(
            name='SuccessfulMpesaTransaction',
        ),
    ]
