# Generated by Django 4.2.23 on 2025-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_location_user_constituency_user_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
