# Generated by Django 4.2.23 on 2025-08-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_user_phone_otp_user_phone_otp_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_expires',
        ),
    ]
