# Generated by Django 4.2.23 on 2025-08-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_phoneotp_remove_user_code_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
