# Generated by Django 4.2.23 on 2025-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_gig_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
