# Generated by Django 4.2.23 on 2025-08-19 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_verificationrequest_user_current_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('county', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_gigs', to='app.organization')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
