# Generated by Django 4.2.23 on 2025-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_organization_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='code',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
