# Generated by Django 4.2.23 on 2025-08-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_jobtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
