# Generated by Django 4.2.23 on 2025-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_gig_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gighistory',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
