# Generated by Django 4.2.23 on 2025-08-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_gighistory_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gighistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_histories', to='app.organization'),
        ),
    ]
