# Generated by Django 4.2.23 on 2025-08-23 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_gighistory_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('action', models.CharField(choices=[('verify_gig', 'Gig Verified'), ('complete_gig', 'Gig Completed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
